title: Will Karmis
header: Will Karmis
description: >- 
  is a sound artist that makes sound sometimes with music and guitar while sitting on a computer and think up ways to make sound while also trying to write a family size open for awesomeness I am drinking coffee right now.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com